name: 自动创建版本号

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Update tag
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}