name: 自动创建版本号

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: butlerlogic/action-autotag@1.0.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex # Optional since regex_pattern is defined
          root: "/version"
          regex_pattern: "([0-9]+\.[0-9]+\.[0-9]+)"